# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temp_entities_dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntityType', models.CharField(max_length=100)),
                ('PlayerName', models.CharField(max_length=100)),
                ('EntityName', models.CharField(max_length=100)),
                ('EntityTitle', models.CharField(max_length=100)),
                ('HealthDescription', models.CharField(max_length=100)),
                ('CatchPhrase', models.CharField(max_length=200)),
            ],
        ),
    ]
